# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-License-Identifier: CC0-1.0

ARG RELEASE=overridden
FROM registry.fedoraproject.org/fedora-minimal:${RELEASE}
RUN --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/tmp \
    --mount=type=tmpfs,target=/var \
    <<EORUN
set -euxo pipefail
# We don't want openh264
rm -f "/etc/yum.repos.d/fedora-cisco-openh264.repo"
# Install ukify & signing tools
dnf install -y systemd-ukify sbsigntools jq
# Temporarily pull bootc from the rhcontainerbot copr to get the latest
# fixes for Bazzite: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/bootc/
dnf install -y 'dnf5-command(copr)'
dnf copr enable -y rhcontainerbot/bootc
dnf install -y bootc
# Prepare output dir
mkdir -p /boot/EFI/Linux
EORUN
